name: Build and Package Python Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pyinstaller 

      - name: Build with PyInstaller
        run: |
          pyinstaller main.py --onefile 

      - name: Create build folder
        run: |
          Remove-Item build -Recurse -Force  # Ordner löschen, falls vorhanden
          mkdir build
          cp -r dist/* build\ 
          if (Test-Path config.txt) { copy config.txt build\ }
          if (Test-Path images) { copy /s /e images build\ } 

      - name: Create archive
        run: |
          7z a build.zip build/* 

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip
